package com.example.gmakers_android.feature.profile

import com.example.gmakers_android.feature.profile.model.Champion

object ChampionList {
    val championNameList = arrayOf(
        Champion(266,"Aatrox"),
        Champion(103,"Ahri"),
        Champion(84,"Akali"),
        Champion(166,"Akshan"),
        Champion(12,"Alistar"),
        Champion(32,"Amumu"),
        Champion(34,"Anivia"),
        Champion(1,"Annie"),
        Champion(523,"Aphelios"),
        Champion(22,"Ashe"),
        Champion(136,"Aurelion Sol"),
        Champion(268,"Azir"),
        Champion(432,"Bard"),
        Champion(53,"Blitzcrank"),
        Champion(63,"Brand"),
        Champion(201,"Braum"),
        Champion(51,"Caitlyn"),
        Champion(164,"Camille"),
        Champion(69,"Cassiopeia"),
        Champion(31,"Cho'Gath"),
        Champion(42,"Corki"),
        Champion(122,"Darius"),
        Champion(131,"Diana"),
        Champion(119,"Draven"),
        Champion(36,"Dr. Mundo"),
        Champion(245,"Ekko"),
        Champion(60,"Elise"),
        Champion(28,"Evelynn"),
        Champion(81,"Ezreal"),
        Champion(9,"Fiddlesticks"),
        Champion(114,"Fiora"),
        Champion(105,"Fizz"),
        Champion(3,"Galio"),
        Champion(41,"Gangplank"),
        Champion(86,"Garen"),
        Champion(150,"Gnar"),
        Champion(79,"Gragas"),
        Champion(104,"Graves"),
        Champion(887,"Gwen"),
        Champion(120,"Hecarim"),
        Champion(74,"Heimerdinger"),
        Champion(420,"Illaoi"),
        Champion(39,"Irelia"),
        Champion(427,"Ivern"),
        Champion(40,"Janna"),
        Champion(59,"Jarvan IV"),
        Champion(24,"Jax"),
        Champion(126,"Jayce"),
        Champion(202,"Jhin"),
        Champion(222,"Jinx"),
        Champion(145,"Kai'Sa"),
        Champion(429,"Kalista"),
        Champion(43,"Karma"),
        Champion(30,"Karthus"),
        Champion(38,"Kassadin"),
        Champion(55,"Katarina"),
        Champion(10,"Kayle"),
        Champion(141,"Kayn"),
        Champion(85,"Kennen"),
        Champion(121,"Kha'Zix"),
        Champion(203,"Kindred"),
        Champion(240,"Kled"),
        Champion(96,"Kog'Maw"),
        Champion(7,"LeBlanc"),
        Champion(64,"Lee Sin"),
        Champion(89,"Leona"),
        Champion(876,"Lillia"),
        Champion(127,"Lissandra"),
        Champion(236,"Lucian"),
        Champion(117,"Lulu"),
        Champion(99,"Lux"),
        Champion(54,"Malphite"),
        Champion(90,"Malzahar"),
        Champion(57,"Maokai"),
        Champion(11,"Master Yi"),
        Champion(21,"Miss Fortune"),
        Champion(62,"Wukong"),
        Champion(82,"Mordekaiser"),
        Champion(25,"Morgana"),
        Champion(267,"Nami"),
        Champion(75,"Nasus"),
        Champion(111,"Nautilus"),
        Champion(518,"Neeko"),
        Champion(76,"Nidalee"),
        Champion(56,"Nocturne"),
        Champion(20,"Nunu & Willump"),
        Champion(2,"Olaf"),
        Champion(61,"Orianna"),
        Champion(516,"Ornn"),
        Champion(80,"Pantheon"),
        Champion(78,"Poppy"),
        Champion(555,"Pyke"),
        Champion(246,"Qiyana"),
        Champion(133,"Quinn"),
        Champion(497,"Rakan"),
        Champion(33,"Rammus"),
        Champion(421,"Rek'Sai"),
        Champion(526,"Rell"),
        Champion(58,"Renekton"),
        Champion(107,"Rengar"),
        Champion(92,"Riven"),
        Champion(68,"Rumble"),
        Champion(13,"Ryze"),
        Champion(360,"Samira"),
        Champion(113,"Sejuani"),
        Champion(235,"Senna"),
        Champion(147,"Seraphine"),
        Champion(875,"Sett"),
        Champion(35,"Shaco"),
        Champion(98,"Shen"),
        Champion(102,"Shyvana"),
        Champion(27,"Singed"),
        Champion(14,"Sion"),
        Champion(15,"Sivir"),
        Champion(72,"Skarner"),
        Champion(37,"Sona"),
        Champion(16,"Soraka"),
        Champion(50,"Swain"),
        Champion(517,"Sylas"),
        Champion(134,"Syndra"),
        Champion(223,"Tahm Kench"),
        Champion(163,"Taliyah"),
        Champion(91,"Talon"),
        Champion(44,"Taric"),
        Champion(17,"Teemo"),
        Champion(412,"Thresh"),
        Champion(18,"Tristana"),
        Champion(48,"Trundle"),
        Champion(23,"Tryndamere"),
        Champion(4,"Twisted Fate"),
        Champion(29,"Twitch"),
        Champion(77,"Udyr"),
        Champion(6,"Urgot"),
        Champion(110,"Varus"),
        Champion(67,"Vayne"),
        Champion(45,"Veigar"),
        Champion(161,"Vel'Koz"),
        Champion(254,"Vi"),
        Champion(234,"Viego"),
        Champion(112,"Viktor"),
        Champion(8,"Vladimir"),
        Champion(106,"Volibear"),
        Champion(19,"Warwick"),
        Champion(498,"Xayah"),
        Champion(101,"Xerath"),
        Champion(5,"Xin Zhao"),
        Champion(157,"Yasuo"),
        Champion(777,"Yone"),
        Champion(83,"Yorick"),
        Champion(350,"Yuumi"),
        Champion(154,"Zac"),
        Champion(238,"Zed"),
        Champion(115,"Ziggs"),
        Champion(26,"Zilean"),
        Champion(142,"Zoe"),
        Champion(143,"Zyra")
    )
}